import LocalizedStrings from 'localized-strings';

export let AnimalFormStrings = new LocalizedStrings({
  en: {
    name: "Name",
    breed: "Breed",
    gender: "Gender",
    adoption: "Adoption",
    birthdate: "Birthdate",
    animalType: "Animal type",
    pickerDefault: "Choose an animal type",
    // choosePhotoButton: "Change profile photo",
    loadingLabel: "Loading...",
    savingLabel: "Saving...",
    editAnimal: "Edit animal",
    createAnimal: "Create animal",
    deleteAnimal: "Delete animal",
    deleteAnimalMessage: "Are you sure you want to delete this animal?",
    cancel: "Cancel",
    confirmDelete: "Yes, delete",
    save: "Save",
    male: "Male",
    female: "Female",
    choosePhoto: "Choose photo",
    uploadPhoto: "Upload photo",
    deletePhoto: "Delete photo",
    deletePhotoMsg: "Are you sure you want to delete this picture?",
    mandatoryFields: "Mandatory fields",
    mandatoryFielsdMsg: "Please add a name and choose an animal type.",
    selectPhoto: "Select photo",
    selectPhotoAlertMsg: "Please select a photo to save",
  },
  es: {
    name: "Nombre",
    breed: "Raza",
    gender: "Genero",
    adoption: "Adopción",
    birthdate: "Fecha de nacimiento",
    animalType: "Tipo de animal",
    pickerDefault: "Elegir un tipo de animal",
    loadingLabel: "Cargando...",
    savingLabel: "Guardando...",
    editAnimal: "Editar animal",
    createAnimal: "Crear animal",
    deleteAnimal: "Eliminar animal",
    deleteAnimalMessage: "Esta seguro de borrar este animal?",
    cancel: "Cancelar",
    confirmDelete: "Si, eliminar",
    save: "Guardar",
    male: "Macho",
    female: "Hembra",
    choosePhoto: "Choose photo",
    uploadPhoto: "Subir foto",
    deletePhoto: "Borrar foto",
    deletePhotoMsg: "Esta seguro de borrar esta foto?",
    mandatoryFields: "Campos obligatorios",
    mandatoryFielsdMsg: "Por favor introduzca un nombre y tipo de animal.",
    selectPhoto: "Seleccionar foto",
    selectPhotoAlertMsg: "Por favor seleccione una foto antes de guardar",
  }
});