import LocalizedStrings from 'localized-strings';

let strings = new LocalizedStrings({
  en:{
    register_title:"Register",
    name: "PHETS",
    tagline:"A new world",
    first_name: "First Name",
    last_name: "Last Name",
    username: "Username",
    email:"Email",
    login: "Login",
    password:"Password",
    confirm_password: "Confirm password",
    register:"Register",
    country: "Country",
    city: "City",
    passwords_dont_match: "Passwords don't match",
    text: "Enter your data",
    address: "Address",
    continue: "continue",
    fill_all: "You must fill all fields",
    loadingLabel: "Loading...",
    pickerDefault: "Choose a country",
  },
  es: {
    register_title:"Registrarse",
    name: "PHETS",
    tagline:"Un nuevo mundo",
    first_name: "Nombre",
    last_name: "Apellido",
    username: "Nombre de usuario",
    email:"Email",
    login: "Iniciar Sesión",
    password:"Contraseña",
    confirm_password: "Confirmar contraseña",
    register:"Registrarse",
    country: "País",
    city: "Ciudad",
    passwords_dont_match: "Las contraseñas no coinciden",
    text: "Ingrese sus datos",
    address: "Dirección",
    continue: "Continuar",
    fill_all: "Debe llenar todos los campos",
    loadingLabel: "Cargando...",
    pickerDefault: "Seleccione un pais",
  }},
);

export { strings };