import LocalizedStrings from 'localized-strings';

export let UserEditionStrings = new LocalizedStrings({
  en: {
    editProfile: "Edit profile",
    name: "Name",
    lastName: "Last name",
    description: "Description",
    country: "Country",
    city: "City",
    save: "Save",
    pickerDefault: "Choose a country",
    choosePhotoButton: "Change profile photo",
    loadingLabel: "Loading...",
    savingLabel: "Saving...",
    editProfile: "Edit profile",
    deleteAccount: "Delete account",
    deleteAccountMessage: "Are you sure you want to delete your account?",
    cancelDelete: "Cancel",
    confirmDelete: "Yes, delete",
  },
  es: {
    editProfile: "Editar perfil",
    name: "Nombre",
    lastName: "Apellido",
    description: "Descripción",
    country: "País",
    city: "Ciudad",
    save: "Guardar",
    pickerDefault: "Elegir país",
    choosePhotoButton: "Cambiar foto de perfil",
    loadingLabel: "Cargando...",
    savingLabel: "Guardando...",
    editProfile: "Editar perfil",
    deleteAccount: "Eliminar cuenta",
    deleteAccountMessage: "Estas seguro de borrar tu cuenta?",
    cancelDelete: "Cancelar",
    confirmDelete: "Si, borrar",
  }
});